[[headers]]
  for = "*.js" # 1 month for js files
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.css" # 1 month for css files
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.jpg" # 1 year for jpg files
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png" # 1 year for png files
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff" # 1 year for woff fonts
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.woff2" # 1 year for woff2 fonts
  [headers.values]
    Cache-Control = "public, max-age=31536000"