- name: Create new release dir
  file:
    path: "{{ deploy_helper.new_release_path }}"
    state: directory
    mode: '0755'

- name: Add an unfinished file, to allow cleanup on successful finalize
  file:
    path: '{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}'
    state: touch

- name: Install npm dependencies
  command: npm install
  delegate_to: localhost
  args:
    chdir: "{{ project_local_path }}"

- name: Compile project
  command: npm run generate
  delegate_to: localhost
  args:
    chdir: "{{ project_local_path }}"

- name: Compress dist folder
  delegate_to: localhost
  archive:
    path: "{{ project_local_path }}/dist/*"
    dest: "{{ project_local_path }}/dist.zip"
    format: zip

- name: Copy dist.zip to remote
  copy:
    src: "{{ project_local_path }}/dist.zip"
    dest: "{{ deploy_helper.new_release_path }}"
    mode: "0755"

- name: Extract dist.zip
  unarchive:
    src: "{{ deploy_helper.new_release_path }}/dist.zip"
    dest: "{{ deploy_helper.new_release_path }}"
    remote_src: yes

- name: Purge unnecessary project files
  shell: "rm -f {{ purge_files_after_deploy | join(' ') }}"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
    warn: false
  when: purge_files_after_deploy is not none
  ignore_errors: yes
